version: '3.1'
services:
  app:
    container_name: springboottest
    image: architdev/springboot
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=client
